
export const shapesMappings={
    "disk":"sftp",
    "map":"messageMapping",
    "message":"contentModifier",
    "processcall":"processCall",
    "processroute":"router",
    "Base64 Decode":"base64Decoder",
    "Base64 Encode":"base64Encoder",
    "Character Decode":"groovyScript",
    "Character Encode":"groovyScript",
    "Combine Documents":"gather",
    "Custom Scripting":"groovyScript",
    "Search/Replace":"messageMapping",
    "Split Documents":"generalSplitter",
    "Mapjsontomultipartformdatamime":"groovyScript",
    "Mapmultipartformdatamimetojson":"groovyScript",
    "Pgp Encrypt":"pgpEncryptor",
    "Pgp Decrypt":"pgpDecryptor",
    'Xslt Ttransformation':"xsltMapping",
    "Zip":"zipCompression",
    "Unzip":"zipDecompression",
    "branch":"parallelMulticast/sequentialMulticast",
    "route":"router",
    "start":"start",
    "stop":"end",
    "catcherrors":"exceptionSubprocess",
    "setproperties":"contentModifier",
    'cache':"NA",
    "flowcontrol":"parallelMulticast",
    "businessrules":"NA",
    "diskconnector":"sftp",
    "customscripting":"groovyScript",
    "documentproperties":"contentModifier",
    'dynamicdocumentproperties':"groovyScript",
    'processproperties':"contentModifier",
    'dynamicprocessproperties':"groovyScript",
    'ftp':"ftp",
    'sftp':"sftp",
    'http':"http",
    'mail':"mail",
    'odata':"odata",
    'rest':"http",
    'salesforce':"salesforce",
    'netsuite':'netsuite',
    'successfactors':'successfactors',
    'wssoapclientsdk':"soap",
    'cleanse':"NA",
    'programcommand':"groovyScript",
    'aws':"openConnector",
    'returndocuments':'end',
    'findchanges':"messageMapping"
}
